apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: blue
      name: blue
    name: blue
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: blue
      name: blue
    name: blue
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: blue:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/wkulhanek/cotd.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.1
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxI2B8A8PdkLqofNwXti
      type: GitHub
    - generic:
        secret: kzNGy3L9TOFeGwjNp_PI
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: blue
      name: blue
    name: blue
  spec:
    replicas: 1
    selector:
      app: blue
      deploymentconfig: blue
      name: blue
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: blue
          deploymentconfig: blue
          name: blue
      spec:
        containers:
        - env:
          - name: SELECTOR
            value: cats
          image: blue:latest
          name: blue
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - blue
        from:
          kind: ImageStreamTag
          name: blue:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: blue
      name: blue
    name: blue
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: blue
      deploymentconfig: blue
      name: blue
  status:
    loadBalancer: {}
kind: List
metadata: {}
