apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-04-30T05:05:35Z
  generation: 4
  labels:
    app: green
    name: green
  name: green
  namespace: pr-ocp-adv-dev
  resourceVersion: "63855"
  selfLink: /oapi/v1/namespaces/pr-ocp-adv-dev/deploymentconfigs/green
  uid: 1dcdd4b2-4c34-11e8-886e-46cfe6b1c4e0
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: green
    deploymentconfig: green
    name: green
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: green
        deploymentconfig: green
        name: green
    spec:
      containers:
      - env:
        - name: SELECTOR
          value: cities
        image: 172.30.1.1:5000/pr-ocp-adv-dev/green@sha256:6dfb25f47e4d28677a256d31982e839e4ba36eda624eb57ae27c3e73710e2e03
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /item.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: green
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /item.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - green
      from:
        kind: ImageStreamTag
        name: green:latest
        namespace: pr-ocp-adv-dev
      lastTriggeredImage: 172.30.1.1:5000/pr-ocp-adv-dev/green@sha256:6dfb25f47e4d28677a256d31982e839e4ba36eda624eb57ae27c3e73710e2e03
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-30T05:06:02Z
    lastUpdateTime: 2018-04-30T05:06:02Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-04-30T06:08:15Z
    lastUpdateTime: 2018-04-30T06:08:16Z
    message: replication controller "green-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 3
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
