apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: logtofile
    name: logtofile
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/wkulhanek/logtofile:latest
      from:
        kind: DockerImage
        name: docker.io/wkulhanek/logtofile:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: logtofile
    name: logtofile
  spec:
    replicas: 1
    selector:
      app: logtofile
      deploymentconfig: logtofile
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: logtofile
          deploymentconfig: logtofile
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - sleep 5 && tail -n+1 -f /tmp/datelog.txt
          image: docker.io/busybox:latest
          imagePullPolicy: Always
          name: logging-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp

        - image: docker.io/wkulhanek/logtofile@sha256:3b696d63235007e9b018ec2f20f3f6c5553842ecdbcb7065966cf9b9cb72a7c0
          imagePullPolicy: Always
          name: logtofile
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        volumes:
        - emptyDir: {}
          name: tmp

    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - logtofile
        from:
          kind: ImageStreamTag
          name: logtofile:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
