apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: blue
    name: blue
  name: bluegreen
spec:
  host: ""
  port:
    targetPort: 8080-tcp
  to:
    kind: ""
    name: blue
    weight: null
status:
  ingress: []
